<a href="https://colab.research.google.com/github/canunz/EV3_outfits/blob/main/Proyecto_Smart_Factory.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Proyecto Smart Factory
### integrantes: Fanny araujo y Catalina Nuñez

**Paso 1:** Configuración del Entorno y Carga de los datos
• Importación de Librerías: Instale y cargue las librerías necesarias para la manipulación de
datos, visualización y preprocesamiento (pandas, numpy, matplotlib, seaborn, sklearn y
otras)

In [ ]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

 Carga del Dataset: Importe el archivo Proyecto_SmartFactory_Falla_Equipos.csv y
almacénelo en un DataFrame llamado df

In [ ]:
data_frame = '/content/drive/MyDrive/2026-1/MINERÍA   DE DATOS/MINERIA DE DATOS EV1/Proyecto_SmartFactory_Falla_Equipos.csv'
data_frame = pd.read_csv(data_frame)
data_frame.head()
print()
print("--------------------------------------")

sns.set_style("whitegrid")
plt.rcParams['figure.figsize'] = (10, 6)
print("Configuración de visualización aplicada: estilo 'whitegrid' de Seaborn y tamaño de figura (10, 6).")

print()
print("--------------------------------------")

print("Información del DataFrame data_frame:")
data_frame.info()
print()
print("--------------------------------------")

print("Valores nulos por columna en data_frame:")
null_counts = data_frame.isnull().sum()
print(null_counts)

# Acá se dentifican columnas con nulos
columns_with_nulls = null_counts[null_counts > 0]

if not columns_with_nulls.empty:
    print(f"\nSe encontraron valores nulos en las siguientes columnas:\n{columns_with_nulls}")

--------------------------------------
Configuración de visualización aplicada: estilo 'whitegrid' de Seaborn y tamaño de figura (10, 6).

--------------------------------------
Información del DataFrame data_frame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   UDI                      10000 non-null  int64
 1   Product ID               10000 non-null  object
 2   Type                     10000 non-null  object
 3   Air temperature [K]      10000 non-null  float64
 4   Process temperature [K]  10000 non-null  float64
 5   Rotational speed [rpm]   10000 non-null  int64
 6   Torque [Nm]              10000 non-null  float64
 7   Tool wear [min]          10000 non-null  int64
 8   Machine failure          10000 non-null  int64
 9   TWF                      10000 non-null  int64
 10  HDF                      10000 non-null  int64
 11  PWF                      10000 non-null  int64
 12  OSF                      10000 non-null  int64
 13  RNF                      10000 non-null  int64
dtypes: float64(3), int64(9), object(2)
memory usage: 1.1+ MB

--------------------------------------
Valores nulos por columna en data_frame:
UDI                        0
Product ID                 0
Type                       0
Air temperature [K]        0
Process temperature [K]    0
Rotational speed [rpm]     0
Torque [Nm]                0
Tool wear [min]            0
Machine failure            0
TWF                        0
HDF                        0
PWF                        0
OSF                        0
RNF                        0
dtype: int64

**Paso 2:** Entendimiento de los Datos
• Dimensiones y Vista Previa: Determine el volumen total de registros (filas) y variables
(columnas)

In [ ]:
data_frame.head()

,UDI,Product ID,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF
0,1,M14860,M,298.1,308.6,1551,42.8,0,0,0,0,0,0,0
1,2,L47181,L,298.2,308.7,1408,46.3,3,0,0,0,0,0,0
2,3,L47182,L,298.1,308.5,1498,49.4,5,0,0,0,0,0,0
3,4,L47183,L,298.2,308.6,1433,39.5,7,0,0,0,0,0,0
4,5,L47184,L,298.2,308.7,1408,40.0,9,0,0,0,0,0,0

In [ ]:
# Selecciona solo las características que se van a considerar en los posteriores análisis
X = data_frame.iloc[:, 3:-1].values
# La ùltima columna (sale o no sale) se separa del resto para analizar laelación que tiene ella con el resto
y = data_frame.iloc[:, -1].values

Visualice las primeras 10 filas para una inspección visual inicial

In [ ]:
pd.DataFrame(X).head(10)

       0      1       2     3     4    5    6    7    8    9
0  298.1  308.6  1551.0  42.8   0.0  0.0  0.0  0.0  0.0  0.0
1  298.2  308.7  1408.0  46.3   3.0  0.0  0.0  0.0  0.0  0.0
2  298.1  308.5  1498.0  49.4   5.0  0.0  0.0  0.0  0.0  0.0
3  298.2  308.6  1433.0  39.5   7.0  0.0  0.0  0.0  0.0  0.0
4  298.2  308.7  1408.0  40.0   9.0  0.0  0.0  0.0  0.0  0.0
5  298.1  308.6  1425.0  41.9  11.0  0.0  0.0  0.0  0.0  0.0
6  298.1  308.6  1558.0  42.4  14.0  0.0  0.0  0.0  0.0  0.0
7  298.1  308.6  1527.0  40.2  16.0  0.0  0.0  0.0  0.0  0.0
8  298.3  308.7  1667.0  28.6  18.0  0.0  0.0  0.0  0.0  0.0
9  298.5  309.0  1741.0  28.0  21.0  0.0  0.0  0.0  0.0  0.0

In [ ]:
pd.DataFrame(y).head(10)

   0
0  1
1  0
2  1
3  0
4  0
5  1
6  0
7  1
8  0
9  0

# 1.1 Transformación de variables categóricas

In [ ]:
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [ ]:
# define example
data = ['frio', 'frio', 'templado','frio', 'calor', 'calor','templado','frio','templado', 'calor']
values = array(data)
print('Valores:',values)
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print('Label encoder integer:',integer_encoded)
# binary encode
onehot_encoder = OneHotEncoder(sparse_output=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print('one-hot encoder:\n', onehot_encoded)
# invert first example
inverted = label_encoder.inverse_transform([argmax(onehot_encoded[0, :])])
print(inverted)

Valores: ['frio' 'frio' 'templado' 'frio' 'calor' 'calor' 'templado' 'frio'
 'templado' 'calor']
Label encoder integer: [1 1 2 1 0 0 2 1 2 0]
one-hot encoder:
 [[0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
['frio']

Analizando el resultado anterior La matriz que aparece junto one-hot-encoder es de 3x3; esto
es porque se tienen tres valores distintos.
Si se revisa la primera fila: [0 1 0] significa que el primer valor corresponde a frío; es decir, la
primera columna representa el valor calor (codificado en 0), la segunda es frio (codificada en 1) y
la tercera columna es templado (codificada en 2).

# 1.1.1 Se comienza con la columna que contiene el género

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
pd.DataFrame(X)

        0        1  2   3   4          5  6  7  8          9
0     619   France  0  42   2        0.0  1  1  1  101348.88
1     608    Spain  0  41   1   83807.86  1  0  1  112542.58
2     502   France  0  42   8   159660.8  3  1  0  113931.57
3     699   France  0  39   1        0.0  2  0  0   93826.63
4     850    Spain  0  43   2  125510.82  1  1  1    79084.1
...   ...      ... ..  ..  ..        ... .. .. ..        ...
9995  771   France  1  39   5        0.0  2  1  0   96270.64
9996  516   France  1  35  10   57369.61  1  1  1  101699.77
9997  709   France  0  36   7        0.0  1  0  1   42085.58
9998  772  Germany  1  42   3   75075.31  2  1  0   92888.52
9999  792   France  0  28   4  130142.79  1  1  0   38190.78

[10000 rows x 10 columns]

In [ ]:
# Primero se revisan los valores únicos
pd.DataFrame(X)[1].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

Se observan 3 valores distintos, por lo que se espera que se agreguen 3 columnas y que cada una de
ellas contenga 0 (ausencia) o 1 (presencia) del valor original

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])],remainder='passthrough')
X = np.array(ct.fit_transform(X))
pd.DataFrame(X)

       0    1    2    3  4   5   6          7  8  9  10         11
0     1.0  0.0  0.0  619  0  42   2        0.0  1  1  1  101348.88
1     0.0  0.0  1.0  608  0  41   1   83807.86  1  0  1  112542.58
2     1.0  0.0  0.0  502  0  42   8   159660.8  3  1  0  113931.57
3     1.0  0.0  0.0  699  0  39   1        0.0  2  0  0   93826.63
4     0.0  0.0  1.0  850  0  43   2  125510.82  1  1  1    79084.1
...   ...  ...  ...  ... ..  ..  ..        ... .. .. ..        ...
9995  1.0  0.0  0.0  771  1  39   5        0.0  2  1  0   96270.64
9996  1.0  0.0  0.0  516  1  35  10   57369.61  1  1  1  101699.77
9997  1.0  0.0  0.0  709  0  36   7        0.0  1  0  1   42085.58
9998  0.0  1.0  0.0  772  1  42   3   75075.31  2  1  0   92888.52
9999  1.0  0.0  0.0  792  0  28   4  130142.79  1  1  0   38190.78

[10000 rows x 12 columns]

# 1.1.2 Comprobando la salida
Se visualizan 3 columnas al inicio de la matriz; si se considera la primera fila es (1,0,0) y sabiendo
que el orden sería (France, Germany y Spain) indica que la primera observación sería de France.
El mismo análisis se hace para la segunda fila (0,0,1) que corresponde a Spain

# 1.2 Escalar las características
Existen varias alternativas:
1. StandardScaler
2. MinMaxScaler

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
scaled_data = sc.fit_transform(X)
pd.DataFrame(scaled_data).head()

,0,1,2,3,4,5,6,7,8,9,10,11
0,0.997204,-0.578736,-0.573809,-0.326221,-1.095988,0.293517,-1.041760,-1.225848,-0.911583,0.646092,0.970243,0.021886
1,-1.002804,-0.578736,1.742740,-0.440036,-1.095988,0.198164,-1.387538,0.117350,-0.911583,-1.547768,0.970243,0.216534
2,0.997204,-0.578736,-0.573809,-1.536794,-1.095988,0.293517,1.032908,1.333053,2.527057,0.646092,-1.030670,0.240687
3,0.997204,-0.578736,-0.573809,0.501521,-1.095988,0.007457,-1.387538,-1.225848,0.807737,-1.547768,-1.030670,-0.108918
4,-1.002804,-0.578736,1.742740,2.063884,-1.095988,0.388871,-1.041760,0.785728,-0.911583,0.646092,0.970243,-0.365276

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaled_data_1 = sc.fit_transform(X)
pd.DataFrame(scaled_data_1).head()

,0,1,2,3,4,5,6,7,8,9,10,11
0,0.997204,-0.578736,-0.573809,-0.326221,-1.095988,0.293517,-1.041760,-1.225848,-0.911583,0.646092,0.970243,0.021886
1,-1.002804,-0.578736,1.742740,-0.440036,-1.095988,0.198164,-1.387538,0.117350,-0.911583,-1.547768,0.970243,0.216534
2,0.997204,-0.578736,-0.573809,-1.536794,-1.095988,0.293517,1.032908,1.333053,2.527057,0.646092,-1.030670,0.240687
3,0.997204,-0.578736,-0.573809,0.501521,-1.095988,0.007457,-1.387538,-1.225848,0.807737,-1.547768,-1.030670,-0.108918
4,-1.002804,-0.578736,1.742740,2.063884,-1.095988,0.388871,-1.041760,0.785728,-0.911583,0.646092,0.970243,-0.365276

In [ ]:
pd.DataFrame(scaled_data_1).describe()

,0,1,2,3,4,5,6,7,8,9,10,11
count,1.000000e+04,1.000000e+04,1.000000e+04,1.000000e+04,1.000000e+04,1.000000e+04,1.000000e+04,1.000000e+04,1.000000e+04,1.000000e+04,1.000000e+04,1.000000e+04
mean,1.143974e-16,-1.989520e-17,5.684342e-17,-4.824585e-16,8.455459e-17,2.414069e-16,-1.325162e-16,6.218670e-15,7.105427e-19,-2.273737e-17,6.394885e-18,3.519141e-15
std,1.000050e+00,1.000050e+00,1.000050e+00,1.000050e+00,1.000050e+00,1.000050e+00,1.000050e+00,1.000050e+00,1.000050e+00,1.000050e+00,1.000050e+00,1.000050e+00
min,-1.002804e+00,-5.787359e-01,-5.738092e-01,-3.109504e+00,-1.095988e+00,-1.994969e+00,-1.733315e+00,-1.225848e+00,-9.115835e-01,-1.547768e+00,-1.030670e+00,-1.740268e+00
25%,-1.002804e+00,-5.787359e-01,-5.738092e-01,-6.883586e-01,-1.095988e+00,-6.600185e-01,-6.959818e-01,-1.225848e+00,-9.115835e-01,-1.547768e+00,-1.030670e+00,-8.535935e-01
50%,9.972039e-01,-5.787359e-01,-5.738092e-01,1.522218e-02,9.124191e-01,-1.832505e-01,-4.425957e-03,3.319639e-01,-9.115835e-01,6.460917e-01,9.702426e-01,1.802807e-03
75%,9.972039e-01,1.727904e+00,-5.738092e-01,6.981094e-01,9.124191e-01,4.842246e-01,6.871299e-01,8.199205e-01,8.077366e-01,6.460917e-01,9.702426e-01,8.572431e-01
max,9.972039e-01,1.727904e+00,1.742740e+00,2.063884e+00,9.124191e-01,5.061197e+00,1.724464e+00,2.795323e+00,4.246377e+00,6.460917e-01,9.702426e-01,1.737200e+00

In [ ]:
df_x = pd.DataFrame(scaled_data)
df_x.head()

,0,1,2,3,4,5,6,7,8,9,10,11
0,0.997204,-0.578736,-0.573809,-0.326221,-1.095988,0.293517,-1.041760,-1.225848,-0.911583,0.646092,0.970243,0.021886
1,-1.002804,-0.578736,1.742740,-0.440036,-1.095988,0.198164,-1.387538,0.117350,-0.911583,-1.547768,0.970243,0.216534
2,0.997204,-0.578736,-0.573809,-1.536794,-1.095988,0.293517,1.032908,1.333053,2.527057,0.646092,-1.030670,0.240687
3,0.997204,-0.578736,-0.573809,0.501521,-1.095988,0.007457,-1.387538,-1.225848,0.807737,-1.547768,-1.030670,-0.108918
4,-1.002804,-0.578736,1.742740,2.063884,-1.095988,0.388871,-1.041760,0.785728,-0.911583,0.646092,0.970243,-0.365276